### PR TITLE
Load code block

### PR DESCRIPTION
**Pull request by hypest**
Note: remember to `git submodule update` to fetch the proper GB branch.

Loads the ported `Code` block from Gutenberg.

* No proper styling ported
* Input box accepts text modifications but are overridden immediately. For the time being text changes only get logged to the console. 
* Test (`'Code block is a TextInput'`) that tests the input component's type (`TextInput` atm)
* The test (`'Code block is a TextInput'`) access the child components using hardcoded array indices 😭

### CODE REVIEW

**Comment by maxme** [comment]
On the `gutenberg/` side, I wonder if we could factorize a bit more of the code. Especially have only one `index.mobile.js` that would be reused (imported) in dummies `index.android.js` and `index.ios.js`.

**Comment by maxme** [comment]
Do you mind adding `multiline={ true }` to the `TextInput` in the plain-text component?

**Comment by maxme** [comment]
Oh and `underlineColorAndroid="transparent"` as well for `android.js`

screenshot-2018-03-21_10 00 02 36

**Comment by hypest** [comment]
> On the gutenberg/ side, I wonder if we could factorize a bit more of the code. Especially have only one index.mobile.js that would be reused (imported) in dummies index.android.js and index.ios.js.

We surely need to do something on that front. Duplicating code like the current code in this PR is only a cause of trouble. Can we do that in a follow up PR though so we don't postpone this one too much?

**Comment by maxme** [comment]
> Can we do that in a follow up PR though so we don't postpone this one too much?

Yes sure.

**Comment by hypest** [comment]
> Do you mind adding multiline={ true } to the TextInput in the plain-text component?

Defo. Was planning to gradually port more stuff from https://github.com/hypest/gbrn-experimental but `multiline` makes sense to port here in this PR. 👍

Done with 4d78fce (and 4d78fce on the GB side).

**Comment by hypest** [comment]
> Oh and underlineColorAndroid="transparent" as well for android.js

Done with 21fff06.

And heh, platform differences already managed to surface 😆. Let's keep the `.android.js` and `.io.js` separate and independent for the time being to let this mature a bit. WDYT @maxme ?

**Comment by maxme** [comment]
Looks good, :shipit:

**Pull request merged**
